apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-db
  labels:
    app: words-db
spec:
  template:
    metadata:
      labels:
        app: words-db
    spec:
      containers:
      - name: kube-db
        image: qnib/k8s-wordsmith-db
        ports:
        - containerPort: 5432
          name: kube-db
