apiVersion: v1
kind: Service
metadata:
  name: kube-db
  labels:
    app: words-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: kube-db
  selector:
    app: words-db
  clusterIP: None
