apiVersion: v1
kind: Service
metadata:
  name: kube-web
  labels:
    app: words-web
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: kube-web
  selector:
    app: words-web
  type: LoadBalancer
