apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-web
  labels:
    app: words-web
spec:
  template:
    metadata:
      labels:
        app: words-web
    spec:
      containers:
      - name: kube-web
        image: qnib/k8s-wordsmith-web
        ports:
        - containerPort: 80
          name: words-web
        env:
        - name: API_HOST
          value: kube-api
